name: Dev API publish
on:
  push:
    branches:
      - master
    tags:
      - 1.*

env:
  DEPLOYMENT_IMAGE: ${{ secrets.AWS_ECR_IMAGE }}:${{ github.ref }}

jobs:
  prebuild:
    name: Pre-build for artifacts
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
        run: echo "Hello world" | tee artifact.txt
      - continue-on-error: false
        uses: actions/upload-artifact@v1
        with:
          name: compile-output
          path: artifact.txt

  build:
    name: Container Issue
    runs-on: ubuntu-latest
    needs: prebuild
    env:
      TAG: dev-${GITHUB_SHA}
    steps:
      - continue-on-error: false
        name: pull
        uses: actions/checkout@v2
      - continue-on-error: false
        uses: actions/download-artifact@v1
        with:
          name: compile-output
          path: artifact.txt
      - continue-on-error: false
        name: Build Container
        run: docker-compose -f docker-compose.wf.yaml build
